### ISSUE TITLE
Invalid syntax in fastai_sentencepiece.py

### ISSUE THREAD

**Issue by cahya-wirawan** [kasparlund/nlp#1]
Hi,
I tried your notebook ULMFiT-Sentencepiece-Wiki-Training, but I get following error
when I executed from `fastai_sentencepiece import *`

```
Traceback (most recent call last):

  File "/home/cahya/Work/miniconda3/envs/fastai-1.0/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-8-5a3a187ba9b4>", line 1, in <module>
    from fastai_sentencepiece import *

  File "/home/cahya/Work/Machine Learning/FastAI/nlp/fastai_sentencepiece.py", line 134
    tl_hash = only_alphas(tl).encode()).hexdigest()
                                      ^
SyntaxError: invalid syntax
```
If I change  
  `tl_hash = only_alphas(tl).encode()).hexdigest()` to 
  `tl_hash = only_alphas(tl).encode().hexdigest()` 
it complains that a list doesn't have "encode" function.

**Comment by tanny411** [comment]
found any solution or workaround? same problem here.
